import {
    FileText, Package, Users, ClipboardList,
    BarChart3, FileBarChart, Globe, Smartphone,
    Server, Zap, Shield, HeadsetIcon, Rocket,
} from 'lucide-react';
import type { ServiceItem, PricingPlan, Project, Differentiator } from '../core/types';

export const SERVICES: ServiceItem[] = [
    {
        icon: FileText,
        title: "Sistema de Facturación",
        desc: "Generá facturas automáticas, llevá control de lo que vendés, y tené tus números claros.",
    },
    {
        icon: Package,
        title: "Gestión de Inventarios",
        desc: "Control total de stock, alertas de reabastecimiento y seguimiento de productos.",
    },
    {
        icon: Users,
        title: "Gestión de Clientes",
        desc: "Llevá un registro ordenado de tus clientes, lo que han comprado, y nunca pierdas un contacto.",
    },
    {
        icon: ClipboardList,
        title: "Gestión de Pedidos",
        desc: "Flujo completo desde la orden hasta la entrega, con seguimiento en cada etapa.",
    },
    {
        icon: BarChart3,
        title: "Resumen de tu Negocio",
        desc: "Mirá cómo va tu negocio de un vistazo: ventas del día, productos más vendidos, ganancias.",
    },
    {
        icon: FileBarChart,
        title: "Reportes Avanzados",
        desc: "Genera reportes personalizados de ventas, operaciones y rendimiento empresarial.",
    },
    {
        icon: Globe,
        title: "Páginas Web",
        desc: "Sitios web corporativos, landings y tiendas online con diseño moderno y responsive.",
    },
    {
        icon: Smartphone,
        title: "Apps Móviles",
        desc: "Aplicaciones nativas para iOS y Android que conectan tu negocio con tus clientes.",
    },
    {
        icon: Server,
        title: "Backend & Arquitectura",
        desc: "APIs robustas, tiempo real y sistemas que escalan con tu negocio, desde microservicios hasta plataformas multi-tenant completas.",
    },
];

export const PROJECTS: Project[] = [
    {
        id: 1,
        title: "TrackDeli — Web Platform",
        category: "Web & Real-Time",
        ecosystem: "trackdeli",
        description: "Plataforma SaaS multi-tenant para logística y delivery: despacho inteligente en tiempo real, mapas interactivos con WebSockets y portal público de seguimiento de pedidos.",
        tags: ["React", "NestJS", "PostgreSQL", "Socket.IO", "Mapbox"],
        image: "/assets/project/webtrack/dash_webtrack.png",
        gallery: [
            "/assets/project/webtrack/dash_webtrack.png",
            "/assets/project/webtrack/pedido_webtrack.png",
            "/assets/project/webtrack/pedidodetalle_webtrack.png",
            "/assets/project/webtrack/riders_webtrack.png",
            "/assets/project/webtrack/tracking_werbtracking.png",
            "/assets/project/webtrack/reportes_webtrack.png",
            "/assets/project/webtrack/comisiones_webtrack.png",
            "/assets/project/webtrack/config_webtrack.png",
        ],
    },
    {
        id: 2,
        title: "TrackDeli — Rider App",
        category: "App Móvil",
        ecosystem: "trackdeli",
        description: "Aplicación móvil en Flutter para repartidores con telemetría GPS continua, recepción automática de órdenes, negociación de tarifas y navegación fluida sincronizada.",
        tags: ["Flutter", "Dart", "Riverpod", "Mapbox", "Firebase", "Socket.IO"],
        image: "/assets/project/appdeli/rutaentrega_app.jpg",
        gallery: [
            "/assets/project/appdeli/rutaentrega_app.jpg",
            "/assets/project/appdeli/taking_app.jpg",
            "/assets/project/appdeli/takepedido_app.jpg",
            "/assets/project/appdeli/listasolicitudes_app.jpg",
            "/assets/project/appdeli/validandoentrega_app.jpg",
            "/assets/project/appdeli/pedidoexitoso_app.jpg",
            "/assets/project/appdeli/historial_app.jpg",
            "/assets/project/appdeli/profile_app.jpg",
        ],
    },
    {
        id: 3,
        title: "TrackDeli POS",
        category: "Punto de Venta",
        ecosystem: "trackdeli",
        description: "Sistema de escritorio con Electron para gestión integral de caja, inventarios y facturación, con soporte nativo para impresoras térmicas ESC/POS y cajón de dinero.",
        tags: ["Electron", "React", "TypeScript", "ESC/POS", "Hardware"],
        image: "/assets/project/pos/order_POS.png",
        gallery: [
            "/assets/project/pos/order_POS.png",
            "/assets/project/pos/caja_POS.png",
            "/assets/project/pos/catalogo_POS.png",
            "/assets/project/pos/order2_POS.png",
            "/assets/project/pos/historial_POS.png",
            "/assets/project/pos/reportes_POS.png",
        ],
    },
    {
        id: 4,
        title: "Dulces Momentos POS",
        category: "Facturación & POS",
        ecosystem: "client",
        description: "Sistema punto de venta completo: facturación rápida, inventario con alertas de stock, control de apertura/cierre de caja (Cash In/Out) y reportes de rentabilidad.",
        tags: ["Facturación", "Inventario", "Caja", "Reportes"],
        image: "/assets/project/DulcesMomentos/project.png",
        gallery: [
            "/assets/project/DulcesMomentos/project.png",
            "/assets/project/DulcesMomentos/gallery/Dash.png",
            "/assets/project/DulcesMomentos/gallery/NuevaOrden.png",
            "/assets/project/DulcesMomentos/gallery/OrdenesTomadas.png",
            "/assets/project/DulcesMomentos/gallery/Pedidos.png",
            "/assets/project/DulcesMomentos/gallery/Productos.png",
            "/assets/project/DulcesMomentos/gallery/Reportes.png",
        ],
    },
    {
        id: 5,
        title: "Sistema de Booking Mopetco",
        category: "Gestión & Reservas",
        ecosystem: "client",
        description: "Plataforma web de citas y gestión de reservas en tiempo real con calendario interactivo, recordatorios automatizados y panel de administración.",
        tags: ["Reservas", "Calendario", "BackOffice", "Automatización"],
        image: "/assets/project/bookingwebsite/project.png",
        gallery: [
            "/assets/project/bookingwebsite/project.png",
            "/assets/project/bookingwebsite/gallery/Services.png",
            "/assets/project/bookingwebsite/gallery/Step1Booking.png",
            "/assets/project/bookingwebsite/gallery/Step2Booking.png",
            "/assets/project/bookingwebsite/gallery/Step3Booking.png",
            "/assets/project/bookingwebsite/gallery/Step4Booking.png",
        ],
    },
    {
        id: 6,
        title: "Landing Page Mopetco",
        category: "Sitio Web",
        ecosystem: "client",
        description: "Sitio web corporativo de alta conversión para empresa de servicios petroleros con diseño premium, SEO técnico avanzado y canal directo a WhatsApp.",
        tags: ["Web", "SEO", "Alta Conversión", "Branding"],
        image: "/assets/project/mopetcowebsite/project.png",
        gallery: [
            "/assets/project/mopetcowebsite/project.png",
            "/assets/project/mopetcowebsite/gallery/Hero.png",
            "/assets/project/mopetcowebsite/gallery/Services.png",
            "/assets/project/mopetcowebsite/gallery/ServiceDetail.png",
            "/assets/project/mopetcowebsite/gallery/Gallery.png",
            "/assets/project/mopetcowebsite/gallery/contact.png",
        ],
    },
    {
        id: 7,
        title: "Legal Track USA",
        category: "App Móvil",
        ecosystem: "external",
        description: "Aplicación móvil multiplataforma para seguimiento en tiempo real de casos de inmigración en EE.UU., feed de video corto optimizado y notificaciones push inmediatas.",
        tags: ["React Native", "Firebase", "Redux", "Push Notifications"],
        image: "/assets/project/legaltrack/img1.png",
        gallery: [
            "/assets/project/legaltrack/img1.png",
            "/assets/project/legaltrack/img2.png",
            "/assets/project/legaltrack/img3.png",
            "/assets/project/legaltrack/img4.png",
        ],
    },
];

export const DIFFERENTIATORS: Differentiator[] = [
    {
        icon: Zap,
        title: "Entrega Rápida",
        desc: "Mientras otros cotizan, nosotros ya vamos por la mitad.",
        stat: "3-5",
        statLabel: "semanas para entrega",
    },
    {
        icon: Shield,
        title: "Código Blindado",
        desc: "Código que no se cae el viernes a las 5pm.",
        stat: "100%",
        statLabel: "test coverage",
    },
    {
        icon: HeadsetIcon,
        title: "Soporte Continuo",
        desc: "No desaparecemos después de entregar. Soporte técnico y mantenimiento incluido.",
        stat: "24/7",
        statLabel: "disponibilidad",
    },
    {
        icon: Rocket,
        title: "Escalabilidad",
        desc: "Sistemas diseñados para crecer contigo. Desde 10 hasta 10,000 usuarios sin reescribir.",
        stat: "∞",
        statLabel: "potencial de escala",
    },
];

export const PLANS: PricingPlan[] = [
    {
        id: 'starter',
        title: "Tu Sitio Web",
        implementationPrice: "desde $300",
        prices: {
            monthly: "$30",
            semiannual: "$26",
            annual: "$23",
        },
        desc: "Todo lo que necesitás para vender online, sin Excel ni dolores de cabeza.",
        devFeatures: [
            "Diseño moderno y adaptable",
            "Formulario de contacto + WhatsApp",
            "Entrega en 1-3 semanas",
            "2 meses de mantenimiento incluidos",
        ],
        membershipFeatures: [
            "Tu sitio siempre online",
            "Soporte cuando lo necesités",
            "Respaldos y seguridad",
        ],
        highlight: false,
        disclaimer: "Después de los 2 meses incluidos: $30/mes",
        cta: "Solicitar mi sitio",
    },
    {
        id: 'pos',
        title: "Sistema de Facturación / POS",
        implementationPrice: "",
        prices: {
            monthly: "$45",
            semiannual: "$40",
            annual: "$35",
        },
        desc: "Todo incluido en una sola cuota mensual. Sin escalones de funciones ni costos ocultos.",
        devFeatures: [
            "Facturación electrónica y comprobantes",
            "Inventario en tiempo real con alertas de stock",
            "Control de caja: aperturas, cierres y arqueos",
            "Reportes avanzados de ventas y rentabilidad",
            "Hardware ESC/POS: impresora térmica y cajón",
            "Multi-usuario con roles configurables",
        ],
        membershipFeatures: [
            "Soporte técnico prioritario",
            "Actualizaciones continuas sin costo extra",
            "Respaldos automáticos en la nube",
        ],
        highlight: true,
        disclaimer: "Precio único mensual todo incluido. Hardware integrado.",
        cta: "Solicitar demo de POS",
    },
    {
        id: 'logistics',
        title: "Logística y Delivery",
        implementationPrice: "",
        prices: {
            monthly: "A convenir",
            semiannual: "A convenir",
            annual: "A convenir",
        },
        desc: "Modelo de comisión por entrega — sin costo fijo mensual, solo pagás cuando tu negocio despacha.",
        devFeatures: [
            "Despacho automático y algoritmo de proximidad",
            "Tracking GPS en tiempo real para cliente final",
            "App nativa para repartidores (Flutter)",
            "Panel administrativo multi-tenant en vivo",
            "Liquidación automática de comisiones",
        ],
        membershipFeatures: [
            "Acompañamiento en puesta en marcha",
            "Monitoreo 24/7 de infraestructura en tiempo real",
            "Soporte directo para la flota de repartidores",
        ],
        highlight: false,
        disclaimer: "Sin costo fijo mensual. Comisiones por volumen de entregas.",
        cta: "Agendar una llamada",
    },
];

export const CONTACT_INFO = {
    email: "contacto@detdevs.com",
    phone: "+505 8806-8133",
    location: "Managua, Nicaragua",
};